### ISSUE TITLE
Update schema on metallb

### ISSUE THREAD

**Issue by m-trojanowski** [datreeio/CRDs-catalog#122]
Hello,
I've noticed that there is a problem with Metallb validation after they introduced new field in  l2advertisement kind:
https://github.com/qingwusunny/fork-metallb/blob/cfff2b9e5f86648e39d4d11ae8aeee02e1dc02ed/config/crd/bases/metallb.io_l2advertisements.yaml
I've already provided pr to address this issue.
Please have a look:
https://github.com/datreeio/CRDs-catalog/pull/121
Thanks in advance!

**Comment by eyarz** [comment]
yes, it's a known problem :(
if the CR owner is updating one of the properties but not releasing a new CRD version it will break the schema validation because the copy in this repo is not up-to-date anymore.

thank you for the PR and if you're interested, I'm looking for help to solve this, so the schemas will always be up-to-date.
